### ISSUE TITLE
Add common market place contracts to exclude from lists for people to filter out for us.

### ISSUE THREAD

**Issue by R-K-H** [Legends-of-Sol/Solana-NFT-collections#2]
There's often NFTs which are encumbered in various contracts which means airdrops may be sent to a contract. Let's not do this so providing a list of things to exclude even for ourselves would be nice.

**Comment by h4rkl** [comment]
This is a great idea. I haven't come across a list of market place and contract addresses before. Would be good to have a source.

**Comment by R-K-H** [comment]
It's been a while but last time I built the lists:

M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K
MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8
CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz
A7p8451ktDCHq5yYaHczeLMYsjRsAkzc3hCXcSrwYHU7
617jbWo616ggkDxvW1Le8pV38XLbVSyWY8ae6QUmGBAU
pAHAKoTJsAAe2ZcvTZUxoYzuygVAFAmbYmJYdWT886r
formn3hJtt8gvVKxpCfzCJGuoz6CNUFcULFZW18iTpC
auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8
hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk

Source https://docs.google.com/spreadsheets/d/101YofaXKHFUJqIxq4mNa4sWnoonmugqlRNHbPj0i440/edit#gid=0

**Comment by h4rkl** [comment]
Have updated the repo with a `common_addresses.json` file. Great reference!
